[package]
name = "byt-runtime"
version = "0.1.0"
edition = "2021"

[dependencies]
deno = "1.29.2"
deno_core = "0.165.0"
deno_runtime = "0.91.0"
aws-config = "0.52.0"
aws-sdk-s3 = "0.22.0"
tokio = "1.21.1"
