[package]
name = "deno-hello"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
deno = "1.29.2"
deno_core = "0.165.0"
deno_runtime = "0.91.0"
tokio = "1.21.1"
